app:
  enviroment: "staging"
  name: "ojnn"
  version: "d3392635b973fe7e94999e070bfd4adf7ca7d7f8"
  host: "dev.ojnn.com.br"
  rCpu: "0.2"
  rMemory: "128Mi"
  lCpu: "0.3"
  lMemory: "256Mi"
  minReplicas: "1"
  maxReplicas: "1"