app:
  enviroment: "production"
  name: "ojnn"
  version: "4865ba1782d1c28a27eccc6b1f22386d1dedb600"
  host: "ojnn.com.br"
  rCpu: "0.2"
  rMemory: "256Mi"
  lCpu: "0.3"
  lMemory: "512Mi"
  minReplicas: "1"
  maxReplicas: "1"