app:
  enviroment: "staging"
  name: "ojnn"
  version: "03a75265d1740062c3b4589e2bb5988ab72869fc"
  host: "dev.ojnn.com.br"
  rCpu: "0.2"
  rMemory: "128Mi"
  lCpu: "0.3"
  lMemory: "256Mi"
  minReplicas: "1"
  maxReplicas: "1"