app:
  enviroment: "production"
  name: "ojnn"
  version: "production-latest"
  host: "ojnn.com.br"
  rCpu: "0.2"
  rMemory: "256Mi"
  lCpu: "0.3"
  lMemory: "512Mi"
  minReplicas: "1"
  maxReplicas: "1"