app:
  enviroment: "production"
  name: "ojnn"
  version: "5874d3d07c8e3fd652e2c7c584285974501cbd3d"
  host: "ojnn.com.br"
  rCpu: "0.2"
  rMemory: "256Mi"
  lCpu: "0.3"
  lMemory: "512Mi"
  minReplicas: "1"
  maxReplicas: "1"