apiVersion: v1
kind: Secret
metadata:
  name: harbor
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.ojnn.com.br": {
          "username": "github",
          "password": "I54]~Y9%72N[U8,p4[?",
          "email": "github@ojnn.com.br",
          "auth": "Z2l0aHViOkk1NF1+WTklNzJOW1U4LHA0Wz8="
        }
      }
    }