apiVersion: v1
kind: Namespace
metadata:
  name: ojnn-staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ojnn-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      app=harbor.ojnn.com.br/homelab/ojnn
    argocd-image-updater.argoproj.io/app.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^staging-.*
    argocd-image-updater.argoproj.io/app.helm.image-tag: app.version
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/harbor-secret
spec:
  project: default
  
  source:
    repoURL: https://github.com/oliveriojnn/ojnn.com.br.git
    targetRevision: dev
    path: Chart
    helm:
      valueFiles:
        - values-staging.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ojnn-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
