name: Deploy ojnn.com.br to Harbor.

on:
  push:
    branches:
      - dev
      - master

permissions:
  contents: write

jobs:
  build-publish-deploy:
    name: Build and Publish to Harbor
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Push - staging
      if: github.ref == 'refs/heads/dev'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/ojnn:staging-${{ github.sha }}

    - name: Update values - staging
      if: github.ref == 'refs/heads/dev'
      run: |
        sed -i 's/version: .*/version: "${{ github.sha }}"/' Chart/values-staging.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Chart/values-staging.yaml
        git commit -m "chore: update staging image to ${{ github.sha }} [skip ci]" || echo "No changes"
        git push || echo "No push needed"

    - name: Build & Push - production
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/ojnn:production-${{ github.sha }}

    - name: Update values - production
      if: github.ref == 'refs/heads/master'
      run: |
        sed -i 's/version: .*/version: "${{ github.sha }}"/' Chart/values-production.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Chart/values-production.yaml
        git commit -m "chore: update production image to ${{ github.sha }} [skip ci]" || echo "No changes"
        git push || echo "No push needed"
